' userの状態遷移図
@startuml{state.png}
title User状態遷移図

[*] -down-> registered
registered -right-> activated : 正式に登録する
activated --> suspended : 凍結される
suspended --> activated : 凍結解除される
suspended --> banned : BANされる
suspended --> deactivated : 退会する
activated --> banned : BANされる
activated --> deactivated : 退会する

@enduml
