@startuml{class.png}
title クラス図

class User {
  id
  email
  crypted_password
}

class UserDetail {
  user_id
  phone_number
  name
  birthday
}

class UserAuthenticationRequest {
  user_id
  id_image
  rejected_at
  authenticated_at
}

class UserSuspension {
  user_id
  removed_at
}

class UserBan {
  user_id
}

class UserClose {
  user_id
}

User "1" - "0..1" UserDetail
User "1" - "*" UserAuthenticationRequest
User "1" - "*" UserSuspension
User "1" - "0..1" UserBan
User "1" - "0..1" UserClose

@enduml
