@startuml{simple-class.png}
title クラス図

class User {
  id
  email
  crypted_password
  status
}

class UserActivation {
  user_id
}

class UserBan {
  user_id
}

class UserDeactivation {
  user_id
}

User "1" - "0..1" UserActivation
User "1" - "0..1" UserBan
User "1" - "0..1" UserDeactivation

@enduml
